services:
  - type: web
    name: movies-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///%kernel.project_dir%/db/movies.db
      - key: CORS_ALLOW_ORIGIN
        value: "*"